// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package appsync

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type UpdateTodoInput struct {
	ID   *string `json:"id"`
	Done *bool   `json:"done"`
}

type User struct {
	ID string `json:"id"`
}
